packages:
  - "packages/booking-calendar"
  - "packages/changelog-timeline"
  - "packages/changelog-timeline/changelog-demo"
  - "packages/booking-calendar/example"
  - "packages/helpers"
  - "packages/react-themes"
  - "packages/shared-i18n"
  - "packages/shared-tokens"
  - "packages/shared-ui-react"
  - "apps/*"
  - "apis/*"
  - "showcases/*/*"
  - "learn/*/*"
  - "libs/*"
  - "tools/export-to-md"
  - "tools/export-to-md/*"