packages:
 - "packages/*"
 - "packages/*/*"
 - "packages/changelog-timeline/changelog-demo"
 - "packages/booking-calendar/example"
 - "apps/*"
 - "apis/*"
 - "showcases/*/*"
 - "learn/*/*"
 - "libs/*"
