// <auto-generated />
using System;
using KidCode.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KidCode.Api.Migrations
{
    [DbContext(typeof(KidCodeDbContext))]
    [Migration("20241213000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KidCode.Api.Models.Challenge", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsDaily").HasColumnType("boolean");
                b.Property<int>("Level").HasColumnType("integer");
                b.Property<string>("Mode").IsRequired().HasColumnType("text");
                b.Property<string>("Prompt").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("RewardSticker").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("StarterBlocksJson").HasColumnType("jsonb");
                b.Property<string>("SuccessCriteria").HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.HasKey("Id");
                b.ToTable("Challenges");
            });

            modelBuilder.Entity("KidCode.Api.Models.Progress", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("BadgesJson").IsRequired().HasColumnType("jsonb");
                b.Property<string>("CompletedChallengesJson").IsRequired().HasColumnType("jsonb");
                b.Property<int>("TotalStickers").HasColumnType("integer");
                b.Property<string>("UnlockedLevelsJson").IsRequired().HasColumnType("jsonb");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("UserId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Progresses");
            });

            modelBuilder.Entity("KidCode.Api.Models.Project", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Assets").HasColumnType("jsonb");
                b.Property<string>("BlocksJson").IsRequired().HasColumnType("jsonb");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Mode").IsRequired().HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("UserId").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Projects");
            });
#pragma warning restore 612, 618
        }
    }
}
