// <auto-generated />
using System;
using KidCode.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KidCode.Api.Migrations
{
    [DbContext(typeof(KidCodeDbContext))]
    [Migration("20241213100000_AddMediaAssets")]
    partial class AddMediaAssets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KidCode.Api.Models.Album", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid?>("CoverMediaId").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("UserId").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Albums");
            });

            modelBuilder.Entity("KidCode.Api.Models.Challenge", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsDaily").HasColumnType("boolean");
                b.Property<int>("Level").HasColumnType("integer");
                b.Property<string>("Mode").IsRequired().HasColumnType("text");
                b.Property<string>("Prompt").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("RewardSticker").HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("StarterBlocksJson").HasColumnType("jsonb");
                b.Property<string>("SuccessCriteria").HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.HasKey("Id");
                b.ToTable("Challenges");
            });

            modelBuilder.Entity("KidCode.Api.Models.MediaAsset", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid?>("AlbumId").HasColumnType("uuid");
                b.Property<byte[]>("Content").IsRequired().HasColumnType("bytea");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<double?>("Duration").HasColumnType("double precision");
                b.Property<string>("FileName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int?>("Height").HasColumnType("integer");
                b.Property<long>("Size").HasColumnType("bigint");
                b.Property<string>("Source").HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("Title").HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("UserId").HasColumnType("text");
                b.Property<int?>("Width").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("AlbumId");
                b.HasIndex("UserId");
                b.ToTable("MediaAssets");
            });

            modelBuilder.Entity("KidCode.Api.Models.Progress", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("BadgesJson").IsRequired().HasColumnType("jsonb");
                b.Property<string>("CompletedChallengesJson").IsRequired().HasColumnType("jsonb");
                b.Property<int>("TotalStickers").HasColumnType("integer");
                b.Property<string>("UnlockedLevelsJson").IsRequired().HasColumnType("jsonb");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("UserId").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Progresses");
            });

            modelBuilder.Entity("KidCode.Api.Models.Project", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Assets").HasColumnType("jsonb");
                b.Property<string>("BlocksJson").IsRequired().HasColumnType("jsonb");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Mode").IsRequired().HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("UserId").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Projects");
            });

            modelBuilder.Entity("KidCode.Api.Models.MediaAsset", b =>
            {
                b.HasOne("KidCode.Api.Models.Album", "Album")
                    .WithMany("MediaAssets")
                    .HasForeignKey("AlbumId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Album");
            });

            modelBuilder.Entity("KidCode.Api.Models.Album", b =>
            {
                b.Navigation("MediaAssets");
            });
#pragma warning restore 612, 618
        }
    }
}
