// <auto-generated />
using System;
using KidCode.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KidCode.Api.Migrations
{
    [DbContext(typeof(KidCodeDbContext))]
    [Migration("20251214221508_AddAlbumVisibilityAndDescription")]
    partial class AddAlbumVisibilityAndDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KidCode.Api.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverMediaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("KidCode.Api.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDaily")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RewardSticker")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StarterBlocksJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1755),
                            IsDaily = false,
                            Level = 1,
                            Mode = "Drawing",
                            Prompt = "Use the Draw Circle block to create your first shape!",
                            RewardSticker = "first-circle",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "hasCircle",
                            Title = "Draw a Circle"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1777),
                            IsDaily = false,
                            Level = 1,
                            Mode = "Drawing",
                            Prompt = "Draw shapes using at least 3 different colors!",
                            RewardSticker = "rainbow-artist",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "colorCount>=3",
                            Title = "Rainbow Colors"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1782),
                            IsDaily = false,
                            Level = 2,
                            Mode = "Drawing",
                            Prompt = "Use Repeat Magic to create a beautiful pattern!",
                            RewardSticker = "pattern-power",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "hasRepeat",
                            Title = "Pattern Power"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1787),
                            IsDaily = false,
                            Level = 1,
                            Mode = "Story",
                            Prompt = "Make your character walk and jump!",
                            RewardSticker = "director-star",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "hasWalk&&hasJump",
                            Title = "Make It Move"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1793),
                            IsDaily = false,
                            Level = 1,
                            Mode = "Story",
                            Prompt = "Make your character say something fun!",
                            RewardSticker = "chatty-star",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "hasSay",
                            Title = "Say Hello"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1797),
                            IsDaily = false,
                            Level = 1,
                            Mode = "Puzzle",
                            Prompt = "Guide your character through the maze to reach the goal!",
                            RewardSticker = "maze-master",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "reachedGoal",
                            Title = "Maze Runner"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2025, 12, 14, 22, 15, 6, 791, DateTimeKind.Utc).AddTicks(1801),
                            IsDaily = false,
                            Level = 1,
                            Mode = "Music",
                            Prompt = "Play 3 notes to create your first melody!",
                            RewardSticker = "music-maker",
                            StarterBlocksJson = "[]",
                            SuccessCriteria = "noteCount>=3",
                            Title = "First Melody"
                        });
                });

            modelBuilder.Entity("KidCode.Api.Models.CharacterAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId");

                    b.ToTable("CharacterAssets");
                });

            modelBuilder.Entity("KidCode.Api.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Mode");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("KidCode.Api.Models.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("ScriptJson")
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("UserId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("KidCode.Api.Models.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CompletedChallengesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EarnedStickersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalStickers")
                        .HasColumnType("integer");

                    b.Property<string>("UnlockedLevelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("KidCode.Api.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assets")
                        .HasColumnType("jsonb");

                    b.Property<string>("BlocksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("KidCode.Api.Models.UserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BadgesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CompletedChallengesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("DrawingGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("DrawingHighScore")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("MusicGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MusicHighScore")
                        .HasColumnType("integer");

                    b.Property<int>("PuzzleGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("PuzzleHighScore")
                        .HasColumnType("integer");

                    b.Property<int>("StoryGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("StoryHighScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStarsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStickers")
                        .HasColumnType("integer");

                    b.Property<string>("UnlockedLevelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DrawingHighScore");

                    b.HasIndex("MusicHighScore");

                    b.HasIndex("PuzzleHighScore");

                    b.HasIndex("StoryHighScore");

                    b.HasIndex("TotalScore");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("KidCode.Api.Models.CharacterAsset", b =>
                {
                    b.HasOne("KidCode.Api.Models.MediaAsset", "MediaAsset")
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("KidCode.Api.Models.MediaAsset", b =>
                {
                    b.HasOne("KidCode.Api.Models.Album", "Album")
                        .WithMany("MediaAssets")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Album");
                });

            modelBuilder.Entity("KidCode.Api.Models.Album", b =>
                {
                    b.Navigation("MediaAssets");
                });
#pragma warning restore 612, 618
        }
    }
}
