// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAutomation.Api.Data;

#nullable disable

namespace TestAutomation.Api.Data.Migrations
{
    [DbContext(typeof(TestAutomationDbContext))]
    [Migration("20251117221800_AddPassedStatusToTestCaseAndTestSuite")]
    partial class AddPassedStatusToTestCaseAndTestSuite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a simplified version - the actual snapshot would include all entities
            // The key changes are adding the Passed property to TestCase and TestSuite

            modelBuilder.Entity("TestAutomation.Api.Models.TestCase", b =>
                {
                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasComment("null = never run, true = passed, false = failed");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestSuite", b =>
                {
                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasComment("null = never run, true = all passed, false = any failed");
                });

#pragma warning restore 612, 618
        }
    }
}
