// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAutomation.Api.Data;

#nullable disable

namespace TestAutomation.Api.Data.Migrations
{
    [DbContext(typeof(TestAutomationDbContext))]
    [Migration("20251119120000_AddSharedImportsToTestFixture")]
    partial class AddSharedImportsToTestFixture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a simplified version - the actual snapshot would include all entities
            // The key changes are adding SharedImportsPath and SharedImportsContent to TestFixture

            modelBuilder.Entity("TestAutomation.Api.Models.TestFixture", b =>
                {
                    b.Property<string>("SharedImportsPath")
                        .HasColumnType("text")
                        .HasComment("Relative path to shared constants/functions for example: import { BASE_URL, loginAsAdmin, resetDb } from '../../shared/test-utils';");

                    b.Property<string>("SharedImportsContent")
                        .HasColumnType("text")
                        .HasComment("Raw TypeScript code to inject: SharedImportsContent is used to inject shared constants/functions into the test file.");
                });

#pragma warning restore 612, 618
        }
    }
}
