// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAutomation.Api.Data;

#nullable disable

namespace TestAutomation.Api.Data.Migrations
{
    [DbContext(typeof(TestAutomationDbContext))]
    [Migration("20251102191510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestAutomation.Api.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.FunctionalRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("FunctionalRequirements");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("ScriptText")
                        .HasColumnType("text");

                    b.Property<string>("Steps")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestDataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedOutput")
                        .HasColumnType("jsonb");

                    b.Property<string>("InputData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestDataSets");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FunctionalRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SetupScript")
                        .HasColumnType("jsonb");

                    b.Property<string>("TeardownScript")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FunctionalRequirementId");

                    b.ToTable("TestFixtures");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("ExecutedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FixtureId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FunctionalRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("JsonReport")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Screenshots")
                        .HasColumnType("jsonb");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestDataSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FunctionalRequirementId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestDataSetId");

                    b.HasIndex("TestRunId");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Browser")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ExecutedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FunctionalRequirementId")
                        .HasColumnType("uuid");

                    b.Property<string>("RunName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedById");

                    b.HasIndex("FunctionalRequirementId");

                    b.HasIndex("Status");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestCase", b =>
                {
                    b.HasOne("TestAutomation.Api.Models.TestSuite", "TestSuite")
                        .WithMany("TestCases")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestDataSet", b =>
                {
                    b.HasOne("TestAutomation.Api.Models.TestCase", "TestCase")
                        .WithMany("TestDataSets")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestFixture", b =>
                {
                    b.HasOne("TestAutomation.Api.Models.FunctionalRequirement", "FunctionalRequirement")
                        .WithMany("TestFixtures")
                        .HasForeignKey("FunctionalRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FunctionalRequirement");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestResult", b =>
                {
                    b.HasOne("TestAutomation.Api.Models.TestFixture", "Fixture")
                        .WithMany("TestResults")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestAutomation.Api.Models.FunctionalRequirement", "FunctionalRequirement")
                        .WithMany("TestResults")
                        .HasForeignKey("FunctionalRequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestAutomation.Api.Models.TestCase", "TestCase")
                        .WithMany("TestResults")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestAutomation.Api.Models.TestDataSet", "TestDataSet")
                        .WithMany("TestResults")
                        .HasForeignKey("TestDataSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestAutomation.Api.Models.TestRun", "TestRun")
                        .WithMany("TestResults")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestAutomation.Api.Models.TestSuite", "TestSuite")
                        .WithMany("TestResults")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fixture");

                    b.Navigation("FunctionalRequirement");

                    b.Navigation("TestCase");

                    b.Navigation("TestDataSet");

                    b.Navigation("TestRun");

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestRun", b =>
                {
                    b.HasOne("TestAutomation.Api.Models.FunctionalRequirement", "FunctionalRequirement")
                        .WithMany("TestRuns")
                        .HasForeignKey("FunctionalRequirementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FunctionalRequirement");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestSuite", b =>
                {
                    b.HasOne("TestAutomation.Api.Models.TestFixture", "Fixture")
                        .WithMany("TestSuites")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.FunctionalRequirement", b =>
                {
                    b.Navigation("TestFixtures");

                    b.Navigation("TestResults");

                    b.Navigation("TestRuns");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestCase", b =>
                {
                    b.Navigation("TestDataSets");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestDataSet", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestFixture", b =>
                {
                    b.Navigation("TestResults");

                    b.Navigation("TestSuites");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestRun", b =>
                {
                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("TestAutomation.Api.Models.TestSuite", b =>
                {
                    b.Navigation("TestCases");

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
