// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAutomation.Api.Data;

#nullable disable

namespace TestAutomation.Api.Data.Migrations
{
    [DbContext(typeof(TestAutomationDbContext))]
    [Migration("20251112230000_AddRemarkToTestFixtures")]
    partial class AddRemarkToTestFixtures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestAutomation.Api.Models.TestFixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("Tracks generation errors and issues found during test file validation");

                    b.ToTable("TestFixtures");
                });

#pragma warning restore 612, 618
        }
    }
}
